export const PERMISSIONS = [
  'members.view',
  'members.create',
  'members.edit',
  'members.export',
  'members.status.change',
  'exams.view',
  'exams.create',
  'exams.edit',
  'exams.export',
  'chat.general.access',
  'chat.trainer.access',
  'chat.youth.access',
  'chat.board.access',
  'chat.clubwork.access',
  'chat.psg.access',
  'polls.create',
  'polls.vote',
  'polls.results.view',
  'calendar.view',
  'calendar.create',
  'calendar.edit',
  'training.view',
  'training.manage',
  'attendance.vote',
  'attendance.manage',
  'users.approve',
  'users.invite',
  'roles.manage',
  'downloads.manage',
  'audit.view',
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

export const STANDARD_ROLE_PERMISSIONS: Record<string, readonly PermissionKey[]> = {
  Vorstand: PERMISSIONS.filter((permission) => permission !== 'chat.psg.access'),
  Trainer: [
    'members.view',
    'exams.view',
    'exams.create',
    'exams.edit',
    'exams.export',
    'chat.general.access',
    'chat.trainer.access',
    'chat.youth.access',
    'polls.create',
    'polls.vote',
    'polls.results.view',
    'calendar.view',
    'calendar.create',
    'training.view',
    'training.manage',
    'attendance.vote',
    'attendance.manage',
  ],
  Jugendtrainer: [
    'members.view',
    'exams.view',
    'exams.create',
    'exams.edit',
    'chat.general.access',
    'chat.trainer.access',
    'polls.create',
    'polls.vote',
    'calendar.view',
    'training.view',
    'attendance.vote',
  ],
  'PSG / Kinderschutz': ['chat.general.access', 'chat.psg.access', 'calendar.view'],
  'Vereinsarbeit / Funktionäre': [
    'chat.general.access',
    'chat.clubwork.access',
    'polls.create',
    'polls.vote',
    'calendar.view',
    'calendar.create',
  ],
  'Mitglied / Eltern': [
    'chat.general.access',
    'polls.vote',
    'calendar.view',
    'training.view',
    'attendance.vote',
  ],
};
